// TICKET-135: inline 14-language map for hardcoded component labels.
// Same pattern as 123 FOOTER_LABELS / 133 HOME_LABELS / 134 LANG_META — keeps
// the template free of an i18n library and lets each section component pull
// its strings from one central source.
//
// Adding a new locale: extend each language sub-object with the same keys, or
// rely on getLabels() per-key fallback to English when an entry is missing.

export const COMPONENT_LABELS: Record<string, Partial<Record<string, string>>> = {
  en: {
    keyFeatures: 'Key Features',
    productsWeOffer: 'Products We Offer',
    learnMore: 'Learn More',
    getAQuoteFor: 'Get a Quote for',
    feature: 'Feature',
    selectAllThatApply: 'Select all that apply',
    needImmediateHelp: 'Need immediate help?',
    callUsDirectly: 'Call us directly:',
    enterYourEmail: 'Enter your email',
    emailAddress: 'Email address',
    blog: 'Blog',
    noArticlesYet: 'No articles yet. Check back soon!',
    latestArticlesFrom: 'Latest articles and insights from',
    readMore: 'Read more',
    backToBlog: 'Back to Blog',
    whatYouGet: 'What You Get',
    subscribe: 'Subscribe',
  },
  zh: {
    keyFeatures: '主要特色',
    productsWeOffer: '提供的产品',
    learnMore: '了解更多',
    getAQuoteFor: '获取报价 -',
    feature: '功能',
    selectAllThatApply: '请勾选所有适用项',
    needImmediateHelp: '需要紧急帮助？',
    callUsDirectly: '直接致电我们：',
    enterYourEmail: '请输入电子邮箱',
    emailAddress: '电子邮箱地址',
    blog: '博客',
    noArticlesYet: '暂无文章，敬请期待！',
    latestArticlesFrom: '最新文章和见解来自',
    readMore: '阅读更多',
    backToBlog: '返回博客',
    whatYouGet: '您将获得',
    subscribe: '订阅',
  },
  fr: {
    keyFeatures: 'Caractéristiques',
    productsWeOffer: 'Nos produits',
    learnMore: 'En savoir plus',
    getAQuoteFor: 'Devis pour',
    feature: 'Caractéristique',
    selectAllThatApply: 'Sélectionnez tout ce qui s\'applique',
    needImmediateHelp: 'Besoin d\'aide immédiate ?',
    callUsDirectly: 'Appelez-nous directement :',
    enterYourEmail: 'Entrez votre e-mail',
    emailAddress: 'Adresse e-mail',
    blog: 'Blog',
    noArticlesYet: 'Aucun article pour le moment. Revenez bientôt !',
    latestArticlesFrom: 'Derniers articles et idées de',
    readMore: 'Lire la suite',
    backToBlog: 'Retour au blog',
    whatYouGet: 'Ce que vous obtenez',
    subscribe: 'S\'abonner',
  },
  es: {
    keyFeatures: 'Características',
    productsWeOffer: 'Nuestros productos',
    learnMore: 'Saber más',
    getAQuoteFor: 'Cotización para',
    feature: 'Característica',
    selectAllThatApply: 'Seleccione todo lo que corresponda',
    needImmediateHelp: '¿Necesita ayuda inmediata?',
    callUsDirectly: 'Llámenos directamente:',
    enterYourEmail: 'Ingrese su correo',
    emailAddress: 'Dirección de correo',
    blog: 'Blog',
    noArticlesYet: 'No hay artículos aún. ¡Vuelva pronto!',
    latestArticlesFrom: 'Últimos artículos y novedades de',
    readMore: 'Leer más',
    backToBlog: 'Volver al blog',
    whatYouGet: 'Lo que obtiene',
    subscribe: 'Suscribirse',
  },
  ja: {
    keyFeatures: '主な特徴',
    productsWeOffer: '取り扱い製品',
    learnMore: '詳細はこちら',
    getAQuoteFor: '見積もり -',
    feature: '機能',
    selectAllThatApply: '該当するものをすべて選択',
    needImmediateHelp: '至急のお問い合わせは？',
    callUsDirectly: 'お電話でのお問い合わせ：',
    enterYourEmail: 'メールアドレスを入力',
    emailAddress: 'メールアドレス',
    blog: 'ブログ',
    noArticlesYet: 'まだ記事はありません。お楽しみに！',
    latestArticlesFrom: '最新の記事とインサイト -',
    readMore: '続きを読む',
    backToBlog: 'ブログに戻る',
    whatYouGet: '提供内容',
    subscribe: '登録する',
  },
  ko: {
    keyFeatures: '주요 기능',
    productsWeOffer: '제공 제품',
    learnMore: '더 알아보기',
    getAQuoteFor: '견적 받기 -',
    feature: '기능',
    selectAllThatApply: '해당하는 모든 항목 선택',
    needImmediateHelp: '즉시 도움이 필요하신가요?',
    callUsDirectly: '직접 전화 주세요:',
    enterYourEmail: '이메일을 입력하세요',
    emailAddress: '이메일 주소',
    blog: '블로그',
    noArticlesYet: '아직 게시글이 없습니다. 곧 다시 확인해 주세요!',
    latestArticlesFrom: '최신 글과 인사이트 -',
    readMore: '더 읽기',
    backToBlog: '블로그로 돌아가기',
    whatYouGet: '받으시는 것',
    subscribe: '구독하기',
  },
  de: {
    keyFeatures: 'Hauptmerkmale',
    productsWeOffer: 'Unsere Produkte',
    learnMore: 'Mehr erfahren',
    getAQuoteFor: 'Angebot für',
    feature: 'Merkmal',
    selectAllThatApply: 'Alle zutreffenden auswählen',
    needImmediateHelp: 'Sofortige Hilfe benötigt?',
    callUsDirectly: 'Rufen Sie uns direkt an:',
    enterYourEmail: 'E-Mail eingeben',
    emailAddress: 'E-Mail-Adresse',
    blog: 'Blog',
    noArticlesYet: 'Noch keine Artikel. Schauen Sie bald wieder vorbei!',
    latestArticlesFrom: 'Aktuelle Artikel und Einblicke von',
    readMore: 'Weiterlesen',
    backToBlog: 'Zurück zum Blog',
    whatYouGet: 'Was Sie erhalten',
    subscribe: 'Abonnieren',
  },
  it: {
    keyFeatures: 'Caratteristiche',
    productsWeOffer: 'I nostri prodotti',
    learnMore: 'Scopri di più',
    getAQuoteFor: 'Preventivo per',
    feature: 'Caratteristica',
    selectAllThatApply: 'Seleziona tutte le voci pertinenti',
    needImmediateHelp: 'Hai bisogno di aiuto immediato?',
    callUsDirectly: 'Chiamaci direttamente:',
    enterYourEmail: 'Inserisci la tua email',
    emailAddress: 'Indirizzo email',
    blog: 'Blog',
    noArticlesYet: 'Nessun articolo ancora. Torna presto!',
    latestArticlesFrom: 'Ultimi articoli e approfondimenti di',
    readMore: 'Continua a leggere',
    backToBlog: 'Torna al blog',
    whatYouGet: 'Cosa ottieni',
    subscribe: 'Iscriviti',
  },
  pt: {
    keyFeatures: 'Características',
    productsWeOffer: 'Nossos produtos',
    learnMore: 'Saiba mais',
    getAQuoteFor: 'Cotação para',
    feature: 'Recurso',
    selectAllThatApply: 'Selecione todas as opções aplicáveis',
    needImmediateHelp: 'Precisa de ajuda imediata?',
    callUsDirectly: 'Ligue-nos diretamente:',
    enterYourEmail: 'Digite seu e-mail',
    emailAddress: 'Endereço de e-mail',
    blog: 'Blog',
    noArticlesYet: 'Ainda não há artigos. Volte em breve!',
    latestArticlesFrom: 'Últimos artigos e insights de',
    readMore: 'Leia mais',
    backToBlog: 'Voltar ao blog',
    whatYouGet: 'O que você recebe',
    subscribe: 'Inscrever-se',
  },
  ru: {
    keyFeatures: 'Ключевые особенности',
    productsWeOffer: 'Наши продукты',
    learnMore: 'Узнать больше',
    getAQuoteFor: 'Расчёт стоимости -',
    feature: 'Особенность',
    selectAllThatApply: 'Выберите все подходящие',
    needImmediateHelp: 'Нужна срочная помощь?',
    callUsDirectly: 'Позвоните нам напрямую:',
    enterYourEmail: 'Введите вашу почту',
    emailAddress: 'Адрес почты',
    blog: 'Блог',
    noArticlesYet: 'Пока нет статей. Загляните позже!',
    latestArticlesFrom: 'Свежие статьи и идеи от',
    readMore: 'Читать далее',
    backToBlog: 'Назад к блогу',
    whatYouGet: 'Что вы получаете',
    subscribe: 'Подписаться',
  },
  vi: {
    keyFeatures: 'Tính năng chính',
    productsWeOffer: 'Sản phẩm của chúng tôi',
    learnMore: 'Tìm hiểu thêm',
    getAQuoteFor: 'Báo giá cho',
    feature: 'Tính năng',
    selectAllThatApply: 'Chọn tất cả các mục phù hợp',
    needImmediateHelp: 'Cần trợ giúp ngay?',
    callUsDirectly: 'Gọi trực tiếp cho chúng tôi:',
    enterYourEmail: 'Nhập email của bạn',
    emailAddress: 'Địa chỉ email',
    blog: 'Blog',
    noArticlesYet: 'Chưa có bài viết. Quay lại sau nhé!',
    latestArticlesFrom: 'Bài viết và thông tin mới nhất từ',
    readMore: 'Đọc thêm',
    backToBlog: 'Quay lại Blog',
    whatYouGet: 'Bạn nhận được gì',
    subscribe: 'Đăng ký',
  },
  ar: {
    keyFeatures: 'الميزات الرئيسية',
    productsWeOffer: 'المنتجات التي نقدمها',
    learnMore: 'اعرف المزيد',
    getAQuoteFor: 'احصل على عرض سعر لـ',
    feature: 'الميزة',
    selectAllThatApply: 'اختر كل ما ينطبق',
    needImmediateHelp: 'تحتاج إلى مساعدة فورية؟',
    callUsDirectly: 'اتصل بنا مباشرة:',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    emailAddress: 'عنوان البريد الإلكتروني',
    blog: 'المدونة',
    noArticlesYet: 'لا توجد مقالات بعد. تحقق قريبًا!',
    latestArticlesFrom: 'أحدث المقالات والرؤى من',
    readMore: 'اقرأ المزيد',
    backToBlog: 'العودة إلى المدونة',
    whatYouGet: 'ما ستحصل عليه',
    subscribe: 'اشترك',
  },
  hi: {
    keyFeatures: 'मुख्य विशेषताएं',
    productsWeOffer: 'हमारे उत्पाद',
    learnMore: 'और जानें',
    getAQuoteFor: 'के लिए कोटेशन',
    feature: 'विशेषता',
    selectAllThatApply: 'जो लागू हो वो सब चुनें',
    needImmediateHelp: 'तुरंत मदद चाहिए?',
    callUsDirectly: 'हमें सीधे कॉल करें:',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    emailAddress: 'ईमेल पता',
    blog: 'ब्लॉग',
    noArticlesYet: 'अभी कोई लेख नहीं। जल्द ही वापस आएँ!',
    latestArticlesFrom: 'से नवीनतम लेख और जानकारी',
    readMore: 'और पढ़ें',
    backToBlog: 'ब्लॉग पर वापस जाएं',
    whatYouGet: 'आपको क्या मिलेगा',
    subscribe: 'सदस्यता लें',
  },
  th: {
    keyFeatures: 'คุณสมบัติหลัก',
    productsWeOffer: 'ผลิตภัณฑ์ของเรา',
    learnMore: 'เรียนรู้เพิ่มเติม',
    getAQuoteFor: 'ใบเสนอราคาสำหรับ',
    feature: 'คุณสมบัติ',
    selectAllThatApply: 'เลือกทั้งหมดที่ใช้ได้',
    needImmediateHelp: 'ต้องการความช่วยเหลือทันที?',
    callUsDirectly: 'โทรหาเราโดยตรง:',
    enterYourEmail: 'กรอกอีเมลของคุณ',
    emailAddress: 'ที่อยู่อีเมล',
    blog: 'บล็อก',
    noArticlesYet: 'ยังไม่มีบทความ กลับมาดูเร็วๆ นี้!',
    latestArticlesFrom: 'บทความและข้อมูลล่าสุดจาก',
    readMore: 'อ่านเพิ่มเติม',
    backToBlog: 'กลับไปที่บล็อก',
    whatYouGet: 'สิ่งที่คุณจะได้รับ',
    subscribe: 'สมัครสมาชิก',
  },
};

// Per-key fallback to English. New keys can be added to the `en` block first
// without requiring an immediate translation pass — every consumer continues
// to render rather than emitting empty strings.
export function getLabels(locale: string): Record<string, string> {
  const localeLabels = COMPONENT_LABELS[locale] ?? {};
  const enLabels = COMPONENT_LABELS.en as Record<string, string>;
  return { ...enLabels, ...localeLabels } as Record<string, string>;
}
