// TICKET-135: inline 14-language map for hardcoded component labels.
// Same pattern as 123 FOOTER_LABELS / 133 HOME_LABELS / 134 LANG_META — keeps
// the template free of an i18n library and lets each section component pull
// its strings from one central source.
//
// Adding a new locale: extend each language sub-object with the same keys, or
// rely on getLabels() per-key fallback to English when an entry is missing.

export const COMPONENT_LABELS: Record<string, Partial<Record<string, string>>> = {
  en: {
    keyFeatures: 'Key Features',
    productsWeOffer: 'Products We Offer',
    learnMore: 'Learn More',
    getAQuoteFor: 'Get a Quote for',
    feature: 'Feature',
    selectAllThatApply: 'Select all that apply',
    needImmediateHelp: 'Need immediate help?',
    callUsDirectly: 'Call us directly:',
    enterYourEmail: 'Enter your email',
    emailAddress: 'Email address',
    blog: 'Blog',
    noArticlesYet: 'No articles yet. Check back soon!',
    latestArticlesFrom: 'Latest articles and insights from',
    readMore: 'Read more',
    backToBlog: 'Back to Blog',
    whatYouGet: 'What You Get',
    subscribe: 'Subscribe',
    outOfFive: 'out of 5',
    reviews: 'reviews',
    home: 'Home',
    // #1631 —— 表单输入框的占位符（BlockLeadForm）。
    formName: 'Name',
    formPhone: 'Phone',
    formEmail: 'Email',
    formNeed: 'What do you need?',
    // #1641 —— 表单组件自己的兜底字（按钮 / 成功提示 / 两句校验 / 提交失败 / 提交中），en 这一行就是改之前写死的原文。
    formSubmit: 'Get a free quote',
    formThanks: 'Thanks! We\'ve got your details and will be in touch.',
    formNeedEmail: 'Please enter your email.',
    formNeedPhone: 'Please enter your phone number.',
    formFailed: 'Something went wrong. Please try again or call us.',
    formSending: 'Sending…',
    // #1552 —— 404 页（app/not-found.tsx）。
    pageNotFound: 'Page not found',
    pageNotFoundBody: 'The page you are looking for doesn\'t exist or has moved.',
    backToHome: 'Back to home',
    // #1640 —— 页脚块四个固定语义的栏名（blocks/footer/Section.tsx）；en 与原 COLUMN_TITLES 逐字相同。
    footerServices: 'Services',
    footerServiceAreas: 'Service areas',
    footerPages: 'Pages',
    footerContact: 'Contact',
  },
  zh: {
    keyFeatures: '主要特色',
    productsWeOffer: '提供的产品',
    learnMore: '了解更多',
    getAQuoteFor: '获取报价 -',
    feature: '功能',
    selectAllThatApply: '请勾选所有适用项',
    needImmediateHelp: '需要紧急帮助？',
    callUsDirectly: '直接致电我们：',
    enterYourEmail: '请输入电子邮箱',
    emailAddress: '电子邮箱地址',
    blog: '博客',
    noArticlesYet: '暂无文章，敬请期待！',
    latestArticlesFrom: '最新文章和见解来自',
    readMore: '阅读更多',
    backToBlog: '返回博客',
    whatYouGet: '您将获得',
    subscribe: '订阅',
    outOfFive: '/ 5 分',
    reviews: '条评价',
    home: '首页',
    formName: '姓名',
    formPhone: '电话',
    formEmail: '邮箱',
    formNeed: '您需要什么服务？',
    formSubmit: '免费获取报价',
    formThanks: '谢谢！我们已收到您的信息，会尽快与您联系。',
    formNeedEmail: '请填写您的邮箱。',
    formNeedPhone: '请填写您的电话号码。',
    formFailed: '出错了，请重试或直接给我们打电话。',
    formSending: '发送中…',
    pageNotFound: '页面不存在',
    pageNotFoundBody: '你要找的页面不存在，或者已经移走了。',
    backToHome: '返回首页',
    footerServices: '服务',
    footerServiceAreas: '服务区域',
    footerPages: '页面',
    footerContact: '联系方式',
  },
  fr: {
    keyFeatures: 'Caractéristiques',
    productsWeOffer: 'Nos produits',
    learnMore: 'En savoir plus',
    getAQuoteFor: 'Devis pour',
    feature: 'Caractéristique',
    selectAllThatApply: 'Sélectionnez tout ce qui s\'applique',
    needImmediateHelp: 'Besoin d\'aide immédiate ?',
    callUsDirectly: 'Appelez-nous directement :',
    enterYourEmail: 'Entrez votre e-mail',
    emailAddress: 'Adresse e-mail',
    blog: 'Blog',
    noArticlesYet: 'Aucun article pour le moment. Revenez bientôt !',
    latestArticlesFrom: 'Derniers articles et idées de',
    readMore: 'Lire la suite',
    backToBlog: 'Retour au blog',
    whatYouGet: 'Ce que vous obtenez',
    subscribe: 'S\'abonner',
    outOfFive: 'sur 5',
    reviews: 'avis',
    home: 'Accueil',
    formName: 'Nom',
    formPhone: 'Téléphone',
    formEmail: 'E-mail',
    formNeed: 'De quoi avez-vous besoin ?',
    formSubmit: 'Obtenir un devis gratuit',
    formThanks: 'Merci ! Nous avons bien reçu vos coordonnées et vous recontacterons.',
    formNeedEmail: 'Veuillez saisir votre e-mail.',
    formNeedPhone: 'Veuillez saisir votre numéro de téléphone.',
    formFailed: 'Une erreur s\'est produite. Réessayez ou appelez-nous.',
    formSending: 'Envoi…',
    pageNotFound: 'Page introuvable',
    pageNotFoundBody: 'La page que vous cherchez n\'existe pas ou a été déplacée.',
    backToHome: 'Retour à l\'accueil',
    footerServices: 'Services',
    footerServiceAreas: 'Zones desservies',
    footerPages: 'Pages',
    footerContact: 'Contact',
  },
  es: {
    keyFeatures: 'Características',
    productsWeOffer: 'Nuestros productos',
    learnMore: 'Saber más',
    getAQuoteFor: 'Cotización para',
    feature: 'Característica',
    selectAllThatApply: 'Seleccione todo lo que corresponda',
    needImmediateHelp: '¿Necesita ayuda inmediata?',
    callUsDirectly: 'Llámenos directamente:',
    enterYourEmail: 'Ingrese su correo',
    emailAddress: 'Dirección de correo',
    blog: 'Blog',
    noArticlesYet: 'No hay artículos aún. ¡Vuelva pronto!',
    latestArticlesFrom: 'Últimos artículos y novedades de',
    readMore: 'Leer más',
    backToBlog: 'Volver al blog',
    whatYouGet: 'Lo que obtiene',
    subscribe: 'Suscribirse',
    outOfFive: 'de 5',
    reviews: 'reseñas',
    home: 'Inicio',
    formName: 'Nombre',
    formPhone: 'Teléfono',
    formEmail: 'Correo electrónico',
    formNeed: '¿Qué necesita?',
    formSubmit: 'Pedir presupuesto gratis',
    formThanks: '¡Gracias! Hemos recibido sus datos y nos pondremos en contacto.',
    formNeedEmail: 'Introduzca su correo electrónico.',
    formNeedPhone: 'Introduzca su número de teléfono.',
    formFailed: 'Algo salió mal. Inténtelo de nuevo o llámenos.',
    formSending: 'Enviando…',
    pageNotFound: 'Página no encontrada',
    pageNotFoundBody: 'La página que buscas no existe o se ha movido.',
    backToHome: 'Volver al inicio',
    footerServices: 'Servicios',
    footerServiceAreas: 'Zonas de servicio',
    footerPages: 'Páginas',
    footerContact: 'Contacto',
  },
  ja: {
    keyFeatures: '主な特徴',
    productsWeOffer: '取り扱い製品',
    learnMore: '詳細はこちら',
    getAQuoteFor: '見積もり -',
    feature: '機能',
    selectAllThatApply: '該当するものをすべて選択',
    needImmediateHelp: '至急のお問い合わせは？',
    callUsDirectly: 'お電話でのお問い合わせ：',
    enterYourEmail: 'メールアドレスを入力',
    emailAddress: 'メールアドレス',
    blog: 'ブログ',
    noArticlesYet: 'まだ記事はありません。お楽しみに！',
    latestArticlesFrom: '最新の記事とインサイト -',
    readMore: '続きを読む',
    backToBlog: 'ブログに戻る',
    whatYouGet: '提供内容',
    subscribe: '登録する',
    outOfFive: '/ 5',
    reviews: '件のレビュー',
    home: 'ホーム',
    formName: 'お名前',
    formPhone: '電話番号',
    formEmail: 'メールアドレス',
    formNeed: 'ご希望の内容',
    formSubmit: '無料で見積もりを依頼',
    formThanks: 'ありがとうございます。内容を確認のうえご連絡いたします。',
    formNeedEmail: 'メールアドレスを入力してください。',
    formNeedPhone: '電話番号を入力してください。',
    formFailed: 'エラーが発生しました。もう一度お試しいただくか、お電話ください。',
    formSending: '送信中…',
    pageNotFound: 'ページが見つかりません',
    pageNotFoundBody: 'お探しのページは存在しないか、移動しました。',
    backToHome: 'ホームに戻る',
    footerServices: 'サービス',
    footerServiceAreas: '対応エリア',
    footerPages: 'ページ',
    footerContact: 'お問い合わせ',
  },
  ko: {
    keyFeatures: '주요 기능',
    productsWeOffer: '제공 제품',
    learnMore: '더 알아보기',
    getAQuoteFor: '견적 받기 -',
    feature: '기능',
    selectAllThatApply: '해당하는 모든 항목 선택',
    needImmediateHelp: '즉시 도움이 필요하신가요?',
    callUsDirectly: '직접 전화 주세요:',
    enterYourEmail: '이메일을 입력하세요',
    emailAddress: '이메일 주소',
    blog: '블로그',
    noArticlesYet: '아직 게시글이 없습니다. 곧 다시 확인해 주세요!',
    latestArticlesFrom: '최신 글과 인사이트 -',
    readMore: '더 읽기',
    backToBlog: '블로그로 돌아가기',
    whatYouGet: '받으시는 것',
    subscribe: '구독하기',
    outOfFive: '/ 5',
    reviews: '개 리뷰',
    home: '홈',
    formName: '이름',
    formPhone: '전화번호',
    formEmail: '이메일',
    formNeed: '필요하신 서비스',
    formSubmit: '무료 견적 받기',
    formThanks: '감사합니다! 정보를 받았으며 곧 연락드리겠습니다.',
    formNeedEmail: '이메일을 입력해 주세요.',
    formNeedPhone: '전화번호를 입력해 주세요.',
    formFailed: '문제가 발생했습니다. 다시 시도하시거나 전화 주세요.',
    formSending: '보내는 중…',
    pageNotFound: '페이지를 찾을 수 없습니다',
    pageNotFoundBody: '찾으시는 페이지가 없거나 이동되었습니다.',
    backToHome: '홈으로 돌아가기',
    footerServices: '서비스',
    footerServiceAreas: '서비스 지역',
    footerPages: '페이지',
    footerContact: '연락처',
  },
  de: {
    keyFeatures: 'Hauptmerkmale',
    productsWeOffer: 'Unsere Produkte',
    learnMore: 'Mehr erfahren',
    getAQuoteFor: 'Angebot für',
    feature: 'Merkmal',
    selectAllThatApply: 'Alle zutreffenden auswählen',
    needImmediateHelp: 'Sofortige Hilfe benötigt?',
    callUsDirectly: 'Rufen Sie uns direkt an:',
    enterYourEmail: 'E-Mail eingeben',
    emailAddress: 'E-Mail-Adresse',
    blog: 'Blog',
    noArticlesYet: 'Noch keine Artikel. Schauen Sie bald wieder vorbei!',
    latestArticlesFrom: 'Aktuelle Artikel und Einblicke von',
    readMore: 'Weiterlesen',
    backToBlog: 'Zurück zum Blog',
    whatYouGet: 'Was Sie erhalten',
    subscribe: 'Abonnieren',
    outOfFive: 'von 5',
    reviews: 'Bewertungen',
    home: 'Startseite',
    formName: 'Name',
    formPhone: 'Telefon',
    formEmail: 'E-Mail',
    formNeed: 'Was benötigen Sie?',
    formSubmit: 'Kostenloses Angebot anfordern',
    formThanks: 'Danke! Wir haben Ihre Angaben erhalten und melden uns bei Ihnen.',
    formNeedEmail: 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
    formNeedPhone: 'Bitte geben Sie Ihre Telefonnummer ein.',
    formFailed: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es erneut oder rufen Sie uns an.',
    formSending: 'Wird gesendet…',
    pageNotFound: 'Seite nicht gefunden',
    pageNotFoundBody: 'Die gesuchte Seite existiert nicht oder wurde verschoben.',
    backToHome: 'Zur Startseite',
    footerServices: 'Leistungen',
    footerServiceAreas: 'Einsatzgebiete',
    footerPages: 'Seiten',
    footerContact: 'Kontakt',
  },
  it: {
    keyFeatures: 'Caratteristiche',
    productsWeOffer: 'I nostri prodotti',
    learnMore: 'Scopri di più',
    getAQuoteFor: 'Preventivo per',
    feature: 'Caratteristica',
    selectAllThatApply: 'Seleziona tutte le voci pertinenti',
    needImmediateHelp: 'Hai bisogno di aiuto immediato?',
    callUsDirectly: 'Chiamaci direttamente:',
    enterYourEmail: 'Inserisci la tua email',
    emailAddress: 'Indirizzo email',
    blog: 'Blog',
    noArticlesYet: 'Nessun articolo ancora. Torna presto!',
    latestArticlesFrom: 'Ultimi articoli e approfondimenti di',
    readMore: 'Continua a leggere',
    backToBlog: 'Torna al blog',
    whatYouGet: 'Cosa ottieni',
    subscribe: 'Iscriviti',
    outOfFive: 'su 5',
    reviews: 'recensioni',
    home: 'Home',
    formName: 'Nome',
    formPhone: 'Telefono',
    formEmail: 'Email',
    formNeed: 'Di cosa hai bisogno?',
    formSubmit: 'Richiedi un preventivo gratuito',
    formThanks: 'Grazie! Abbiamo ricevuto i tuoi dati e ti ricontatteremo.',
    formNeedEmail: 'Inserisci la tua email.',
    formNeedPhone: 'Inserisci il tuo numero di telefono.',
    formFailed: 'Qualcosa è andato storto. Riprova o chiamaci.',
    formSending: 'Invio in corso…',
    pageNotFound: 'Pagina non trovata',
    pageNotFoundBody: 'La pagina che cerchi non esiste o è stata spostata.',
    backToHome: 'Torna alla home',
    footerServices: 'Servizi',
    footerServiceAreas: 'Zone servite',
    footerPages: 'Pagine',
    footerContact: 'Contatti',
  },
  pt: {
    keyFeatures: 'Características',
    productsWeOffer: 'Nossos produtos',
    learnMore: 'Saiba mais',
    getAQuoteFor: 'Cotação para',
    feature: 'Recurso',
    selectAllThatApply: 'Selecione todas as opções aplicáveis',
    needImmediateHelp: 'Precisa de ajuda imediata?',
    callUsDirectly: 'Ligue-nos diretamente:',
    enterYourEmail: 'Digite seu e-mail',
    emailAddress: 'Endereço de e-mail',
    blog: 'Blog',
    noArticlesYet: 'Ainda não há artigos. Volte em breve!',
    latestArticlesFrom: 'Últimos artigos e insights de',
    readMore: 'Leia mais',
    backToBlog: 'Voltar ao blog',
    whatYouGet: 'O que você recebe',
    subscribe: 'Inscrever-se',
    outOfFive: 'de 5',
    reviews: 'avaliações',
    home: 'Início',
    formName: 'Nome',
    formPhone: 'Telefone',
    formEmail: 'E-mail',
    formNeed: 'Do que você precisa?',
    formSubmit: 'Pedir orçamento grátis',
    formThanks: 'Obrigado! Recebemos seus dados e entraremos em contato.',
    formNeedEmail: 'Informe seu e-mail.',
    formNeedPhone: 'Informe seu número de telefone.',
    formFailed: 'Algo deu errado. Tente novamente ou ligue para nós.',
    formSending: 'Enviando…',
    pageNotFound: 'Página não encontrada',
    pageNotFoundBody: 'A página que você procura não existe ou foi movida.',
    backToHome: 'Voltar ao início',
    footerServices: 'Serviços',
    footerServiceAreas: 'Áreas atendidas',
    footerPages: 'Páginas',
    footerContact: 'Contato',
  },
  ru: {
    keyFeatures: 'Ключевые особенности',
    productsWeOffer: 'Наши продукты',
    learnMore: 'Узнать больше',
    getAQuoteFor: 'Расчёт стоимости -',
    feature: 'Особенность',
    selectAllThatApply: 'Выберите все подходящие',
    needImmediateHelp: 'Нужна срочная помощь?',
    callUsDirectly: 'Позвоните нам напрямую:',
    enterYourEmail: 'Введите вашу почту',
    emailAddress: 'Адрес почты',
    blog: 'Блог',
    noArticlesYet: 'Пока нет статей. Загляните позже!',
    latestArticlesFrom: 'Свежие статьи и идеи от',
    readMore: 'Читать далее',
    backToBlog: 'Назад к блогу',
    whatYouGet: 'Что вы получаете',
    subscribe: 'Подписаться',
    outOfFive: 'из 5',
    reviews: 'отзывов',
    home: 'Главная',
    formName: 'Имя',
    formPhone: 'Телефон',
    formEmail: 'Эл. почта',
    formNeed: 'Что вам нужно?',
    formSubmit: 'Получить бесплатный расчёт',
    formThanks: 'Спасибо! Мы получили ваши данные и свяжемся с вами.',
    formNeedEmail: 'Укажите ваш email.',
    formNeedPhone: 'Укажите ваш номер телефона.',
    formFailed: 'Что-то пошло не так. Попробуйте ещё раз или позвоните нам.',
    formSending: 'Отправка…',
    pageNotFound: 'Страница не найдена',
    pageNotFoundBody: 'Страница, которую вы ищете, не существует или была перемещена.',
    backToHome: 'На главную',
    footerServices: 'Услуги',
    footerServiceAreas: 'Районы обслуживания',
    footerPages: 'Страницы',
    footerContact: 'Контакты',
  },
  vi: {
    keyFeatures: 'Tính năng chính',
    productsWeOffer: 'Sản phẩm của chúng tôi',
    learnMore: 'Tìm hiểu thêm',
    getAQuoteFor: 'Báo giá cho',
    feature: 'Tính năng',
    selectAllThatApply: 'Chọn tất cả các mục phù hợp',
    needImmediateHelp: 'Cần trợ giúp ngay?',
    callUsDirectly: 'Gọi trực tiếp cho chúng tôi:',
    enterYourEmail: 'Nhập email của bạn',
    emailAddress: 'Địa chỉ email',
    blog: 'Blog',
    noArticlesYet: 'Chưa có bài viết. Quay lại sau nhé!',
    latestArticlesFrom: 'Bài viết và thông tin mới nhất từ',
    readMore: 'Đọc thêm',
    backToBlog: 'Quay lại Blog',
    whatYouGet: 'Bạn nhận được gì',
    subscribe: 'Đăng ký',
    outOfFive: 'trên 5',
    reviews: 'đánh giá',
    home: 'Trang chủ',
    formName: 'Họ tên',
    formPhone: 'Số điện thoại',
    formEmail: 'Email',
    formNeed: 'Bạn cần gì?',
    formSubmit: 'Nhận báo giá miễn phí',
    formThanks: 'Cảm ơn bạn! Chúng tôi đã nhận được thông tin và sẽ liên hệ sớm.',
    formNeedEmail: 'Vui lòng nhập email của bạn.',
    formNeedPhone: 'Vui lòng nhập số điện thoại của bạn.',
    formFailed: 'Đã xảy ra lỗi. Vui lòng thử lại hoặc gọi cho chúng tôi.',
    formSending: 'Đang gửi…',
    pageNotFound: 'Không tìm thấy trang',
    pageNotFoundBody: 'Trang bạn tìm không tồn tại hoặc đã được chuyển đi.',
    backToHome: 'Về trang chủ',
    footerServices: 'Dịch vụ',
    footerServiceAreas: 'Khu vực phục vụ',
    footerPages: 'Trang',
    footerContact: 'Liên hệ',
  },
  ar: {
    keyFeatures: 'الميزات الرئيسية',
    productsWeOffer: 'المنتجات التي نقدمها',
    learnMore: 'اعرف المزيد',
    getAQuoteFor: 'احصل على عرض سعر لـ',
    feature: 'الميزة',
    selectAllThatApply: 'اختر كل ما ينطبق',
    needImmediateHelp: 'تحتاج إلى مساعدة فورية؟',
    callUsDirectly: 'اتصل بنا مباشرة:',
    enterYourEmail: 'أدخل بريدك الإلكتروني',
    emailAddress: 'عنوان البريد الإلكتروني',
    blog: 'المدونة',
    noArticlesYet: 'لا توجد مقالات بعد. تحقق قريبًا!',
    latestArticlesFrom: 'أحدث المقالات والرؤى من',
    readMore: 'اقرأ المزيد',
    backToBlog: 'العودة إلى المدونة',
    whatYouGet: 'ما ستحصل عليه',
    subscribe: 'اشترك',
    outOfFive: 'من 5',
    reviews: 'تقييمات',
    home: 'الرئيسية',
    formName: 'الاسم',
    formPhone: 'الهاتف',
    formEmail: 'البريد الإلكتروني',
    formNeed: 'ما الذي تحتاجه؟',
    formSubmit: 'احصل على عرض سعر مجاني',
    formThanks: 'شكرًا! استلمنا بياناتك وسنتواصل معك.',
    formNeedEmail: 'يرجى إدخال بريدك الإلكتروني.',
    formNeedPhone: 'يرجى إدخال رقم هاتفك.',
    formFailed: 'حدث خطأ ما. يرجى المحاولة مرة أخرى أو الاتصال بنا.',
    formSending: 'جارٍ الإرسال…',
    pageNotFound: 'الصفحة غير موجودة',
    pageNotFoundBody: 'الصفحة التي تبحث عنها غير موجودة أو تم نقلها.',
    backToHome: 'العودة إلى الرئيسية',
    footerServices: 'الخدمات',
    footerServiceAreas: 'مناطق الخدمة',
    footerPages: 'الصفحات',
    footerContact: 'تواصل معنا',
  },
  hi: {
    keyFeatures: 'मुख्य विशेषताएं',
    productsWeOffer: 'हमारे उत्पाद',
    learnMore: 'और जानें',
    getAQuoteFor: 'के लिए कोटेशन',
    feature: 'विशेषता',
    selectAllThatApply: 'जो लागू हो वो सब चुनें',
    needImmediateHelp: 'तुरंत मदद चाहिए?',
    callUsDirectly: 'हमें सीधे कॉल करें:',
    enterYourEmail: 'अपना ईमेल दर्ज करें',
    emailAddress: 'ईमेल पता',
    blog: 'ब्लॉग',
    noArticlesYet: 'अभी कोई लेख नहीं। जल्द ही वापस आएँ!',
    latestArticlesFrom: 'से नवीनतम लेख और जानकारी',
    readMore: 'और पढ़ें',
    backToBlog: 'ब्लॉग पर वापस जाएं',
    whatYouGet: 'आपको क्या मिलेगा',
    subscribe: 'सदस्यता लें',
    outOfFive: 'में से 5',
    reviews: 'समीक्षाएं',
    home: 'होम',
    formName: 'नाम',
    formPhone: 'फ़ोन',
    formEmail: 'ईमेल',
    formNeed: 'आपको क्या चाहिए?',
    formSubmit: 'मुफ़्त कोटेशन पाएँ',
    formThanks: 'धन्यवाद! हमें आपका विवरण मिल गया है, हम जल्द संपर्क करेंगे।',
    formNeedEmail: 'कृपया अपना ईमेल दर्ज करें।',
    formNeedPhone: 'कृपया अपना फ़ोन नंबर दर्ज करें।',
    formFailed: 'कुछ गलत हो गया। कृपया फिर से कोशिश करें या हमें कॉल करें।',
    formSending: 'भेजा जा रहा है…',
    pageNotFound: 'पेज नहीं मिला',
    pageNotFoundBody: 'आप जो पेज ढूँढ रहे हैं वह मौजूद नहीं है या हटा दिया गया है।',
    backToHome: 'होम पर वापस जाएँ',
    footerServices: 'सेवाएँ',
    footerServiceAreas: 'सेवा क्षेत्र',
    footerPages: 'पेज',
    footerContact: 'संपर्क',
  },
  th: {
    keyFeatures: 'คุณสมบัติหลัก',
    productsWeOffer: 'ผลิตภัณฑ์ของเรา',
    learnMore: 'เรียนรู้เพิ่มเติม',
    getAQuoteFor: 'ใบเสนอราคาสำหรับ',
    feature: 'คุณสมบัติ',
    selectAllThatApply: 'เลือกทั้งหมดที่ใช้ได้',
    needImmediateHelp: 'ต้องการความช่วยเหลือทันที?',
    callUsDirectly: 'โทรหาเราโดยตรง:',
    enterYourEmail: 'กรอกอีเมลของคุณ',
    emailAddress: 'ที่อยู่อีเมล',
    blog: 'บล็อก',
    noArticlesYet: 'ยังไม่มีบทความ กลับมาดูเร็วๆ นี้!',
    latestArticlesFrom: 'บทความและข้อมูลล่าสุดจาก',
    readMore: 'อ่านเพิ่มเติม',
    backToBlog: 'กลับไปที่บล็อก',
    whatYouGet: 'สิ่งที่คุณจะได้รับ',
    subscribe: 'สมัครสมาชิก',
    outOfFive: 'จาก 5',
    reviews: 'รีวิว',
    home: 'หน้าแรก',
    formName: 'ชื่อ',
    formPhone: 'เบอร์โทรศัพท์',
    formEmail: 'อีเมล',
    formNeed: 'คุณต้องการอะไร?',
    formSubmit: 'ขอใบเสนอราคาฟรี',
    formThanks: 'ขอบคุณ! เราได้รับข้อมูลของคุณแล้วและจะติดต่อกลับ',
    formNeedEmail: 'กรุณากรอกอีเมลของคุณ',
    formNeedPhone: 'กรุณากรอกหมายเลขโทรศัพท์ของคุณ',
    formFailed: 'เกิดข้อผิดพลาด กรุณาลองอีกครั้งหรือโทรหาเรา',
    formSending: 'กำลังส่ง…',
    pageNotFound: 'ไม่พบหน้านี้',
    pageNotFoundBody: 'ไม่มีหน้าที่คุณกำลังหา หรือหน้านั้นถูกย้ายไปแล้ว',
    backToHome: 'กลับหน้าแรก',
    footerServices: 'บริการ',
    footerServiceAreas: 'พื้นที่ให้บริการ',
    footerPages: 'หน้า',
    footerContact: 'ติดต่อ',
  },
};

// Per-key fallback to English. New keys can be added to the `en` block first
// without requiring an immediate translation pass — every consumer continues
// to render rather than emitting empty strings.
export function getLabels(locale: string): Record<string, string> {
  const localeLabels = COMPONENT_LABELS[locale] ?? {};
  const enLabels = COMPONENT_LABELS.en as Record<string, string>;
  return { ...enLabels, ...localeLabels } as Record<string, string>;
}
