#!/usr/bin/env node
// ══════════════════════════════════════════════════════════════════════════════════════════════════
// sheet-fresh.js — 池里那 80 份表，跟它们的生成器还对得上吗？（#1016 r2）
// ══════════════════════════════════════════════════════════════════════════════════════════════════
//
//   node scripts/theme-pipeline/sheet-fresh.js --tree <tree-ish|index> --file <路径> --check
//   node scripts/theme-pipeline/sheet-fresh.js --tree index --file <路径>          # 不带 --check = 重新生成它
//
// 路径按**仓库根**写（`templates/nextjs/public/themes/magenta-01.css`），因为叫它的人是
// `ai-team/dispatcher/ship-check-testmap-fresh.sh`，那个守卫从仓库根跑、拿到的也是仓库根的路径。
//
// 退出码按 #741 那家守卫的约定：0 = 跟这棵树的源对得上 · 1 = 过期了 · 2 = 什么都没验成。
//
// ── 为什么需要它（QA2 在 #1016 r1 抓到的）───────────────────────────────────────────────────────
// 那 80 份表头两行写着「generated by scripts/theme-pipeline/generate.js」，而 `ship-check-testmap-fresh.sh`
// 是**按这个横幅**发现生成物的（它的 N5：发现，不是硬编码清单）。发现了却没有登记生成器 ⟹ 它判不出
// 这些文件是不是过期的，按自己的约定就不许报干净 ⟹ rc=1，交付带着一个红的守卫上主干。
//
// 🔴 两条修法里选了这一条（另一条是「把横幅那句话去掉」），理由是**这些表真的是生成的、而且真的复算得出来**：
//   · 一份表 = `sheetFor(i, seed)` 的纯函数产物，而 `(i, seed)` 就写在它自己横幅的候选号 `gen-<seed>-<i+1>` 里。
//     实测 80/80 逐字节复现（#1016 r2 的读数）。
//   · 这个依赖是**活的**，不是理论风险：`sheet-recipes.js` / `palette.js` / `theme-css-lint.js` 的
//     `HOOK_CLASSES` 三天前才被 #1051 改过（7/213 钩子 → 213/213），以后每加一个块还会再动。
//     改了配方而不重新生成，80 份表就一起变成陈述过去的假话，且**没有任何东西会红**。
//   · 去掉横幅则是把 17 万行生成出来的 CSS 对这家守卫**永久隐身** —— 正是 #729/#750 要治的那个形状
//     （东西在、从没接线、于是静默地不存在）。
//
// ── 只读被判的那棵树 ──────────────────────────────────────────────────────────────────────────────
// 源码从 `git cat-file` 取，不读工作树 —— 守卫问的是「**这棵树**里的表跟**这棵树**里的配方对不对得上」，
// 掺进工作树就等于换了个问题答。三份源提到临时目录里再 require（`sheet-recipes.js` 用 `__dirname`
// 找同伴，所以目录层级要照原样摆）。同一棵树只提一次，80 次调用共用（守卫是逐个文件叫的）。
'use strict';

const fs = require('fs');
const os = require('os');
const path = require('path');
const { execFileSync } = require('child_process');

const REPO = path.resolve(__dirname, '..', '..', '..', '..');
// 一份表的全部源：配方本身、调色板、钩子清单（配方按 HOOK_CLASSES 逐个钩子写规则）。
// 第四个是 `theme-css-lint.js` 加载时**自己要读**的角色表 —— 少了它那个模块当场 exit 2 而不是静默空集
// （它文件头写了理由），于是这里也读不成配方。清单漏一份的方向是「什么都没验成」，不是「验过了」。
//
// 🔴 后面四份是 #1016 r4 加的，理由跟前面几份完全一样：配方挑颜色档位时要问「这个档位在 6 组配色
//    预设 × 全部色相档下还够黑吗」，所以 `theme-presets.js`（那 6 组的值）· `theme-contrast.js`
//    （色相档位清单）· `tweaks.js`（转色相那个函数）现在**真的决定那 80 份表长什么样**。
//    `theme-settings.js` 不被配方直接 require，但 `theme-presets.js` 加载时要读它（`:24`）——
//    **清单要的是依赖闭包，不是直接依赖那一层**：漏了它这里就 require 不成配方，方向是「什么都没验成」。
//    不登记的后果不是这个脚本坏掉，是：以后谁给 `theme-presets.js` 加第 7 组配色，80 份表当场全部
//    过期，而**没有任何东西会红** —— 那正是这个脚本存在的理由（见上面「为什么需要它」）。
const SOURCES = [
  'templates/nextjs/scripts/theme-css-lint.js',
  'templates/nextjs/src/lib/sections/block-roles.json',
  'templates/nextjs/scripts/theme-pipeline/palette.js',
  'templates/nextjs/scripts/theme-pipeline/sheet-recipes.js',
  'templates/nextjs/scripts/theme-presets.js',
  'templates/nextjs/scripts/theme-settings.js',
  'templates/nextjs/scripts/theme-contrast.js',
  'templates/nextjs/scripts/tweaks.js',
];
const RECIPES = 'templates/nextjs/scripts/theme-pipeline/sheet-recipes.js';

function git(args) {
  return execFileSync('git', args, { cwd: REPO, maxBuffer: 1 << 28 }).toString();
}

function die(msg) {
  process.stderr.write(`🔴 ${msg}\n`);
  process.exit(2);
}

// ── #1095：postcss 从哪儿借 ────────────────────────────────────────────────────────────────────────
//
// `theme-css-lint.js` 顶上 `require('postcss')` / `require('postcss-value-parser')`，而 `node_modules`
// 不在任何一棵树里（.gitignore）—— 所以下面 exportSources() 只能从某个装过依赖的目录借一份进去。
//
// 🔴 以前那一行写死了 `<REPO>/templates/nextjs/node_modules`，而 `REPO` 是从**这个脚本自己的位置**
//    算出来的。于是在一棵刚 `git worktree add` 出来、没跑过 `npm ci` 的树里，那个 symlink 指向一个
//    不存在的目录，`require` 当场 `Cannot find module 'postcss'`，脚本退 2，叫它的守卫
//    （`ai-team/dispatcher/ship-check-testmap-fresh.sh`）把 80 份表全部记成「什么都没验成」也退 2。
//    而 PM ship 的标准形态**就是**那种树 ⟹ 这一格在最该起作用的地方恒红，且 rc=2 按规矩不许 --ack
//    （`ai-team/SHIPPING.md`）。#1082 那次是 PM 手工 symlink 才把这一格弄成真的审过了。
//
// 修法是让它自己去找：本树没有就去**主工作树**找。链接 worktree 的 `--git-common-dir` 指的是主仓的
// `.git`，它的上一级就是主工作树的根。找不到就 die(2) 并给一条能跑通的命令 —— 不许降成 1、也不许
// 静默跳过（那两种都会把「没查」读成「查过且干净」）。
//
// 📌 借来的依赖**不会改变判决**，这一点是可核的：`sheet-recipes.js` 从 `theme-css-lint.js` 只取
//    `HOOK_CLASSES`，而那个值是对同文件里一个字面量 `HOOKS` 集合做 filter/map 得来的，postcss 只在
//    模块加载时被 require、不参与算它。所以借的确实只是「让那个模块加载得起来」。
// 📌 判据只看 `postcss` 在不在：它是本票要治的那条报错点名的模块。以后哪份源多 require 一个别的模块
//    而借来的目录里没有，走的是文件末尾那个崩溃处理 —— 退 2 并把模块名原样打出来。响亮，不静默。
function resolveNodeModules() {
  const tried = [];
  const consider = (dir) => {
    if (!dir || tried.includes(dir)) return null;
    tried.push(dir);
    return fs.existsSync(path.join(dir, 'postcss')) ? dir : null;
  };
  let found = consider(path.join(REPO, 'templates', 'nextjs', 'node_modules'));
  if (!found) {
    let mainRoot = null;
    try {
      // 普通 clone 里这条返回相对路径 `.git` ⟹ 算回来就是 REPO 自己，被上面的去重挡掉。
      mainRoot = path.dirname(path.resolve(REPO, git(['rev-parse', '--git-common-dir']).trim()));
    } catch (e) {
      mainRoot = null;
    }
    if (mainRoot) found = consider(path.join(mainRoot, 'templates', 'nextjs', 'node_modules'));
  }
  if (found) return found;
  die('找不到能借的 node_modules —— 一份表的配方要 require(\'postcss\')，而 node_modules 不在任何一棵树里。\n'
    + `   找过这些地方：\n${tried.map((d) => `     ${d}`).join('\n')}\n`
    + '   ⟹ 什么都没验成（不是「过期了」）。在这棵树里把依赖备齐再跑，二选一：\n'
    + `     ln -s <装过依赖的仓>/templates/nextjs/node_modules ${path.join(REPO, 'templates/nextjs/node_modules')}\n`
    + `     (cd ${path.join(REPO, 'templates/nextjs')} && npm ci)`);
  return null;   // die() 不返回；写在这里只为让读的人看得出这个函数的出口有两个
}

/** `index` 跟 gen-test-map.py 同义：`git write-tree` —— 它不动工作树、不移动任何 ref。 */
function resolveTree(ref) {
  try {
    if (ref === 'index') return git(['write-tree']).trim();
    return git(['rev-parse', '-q', '--verify', `${ref}^{tree}`]).trim();
  } catch (e) {
    return die(`'${ref}' 在这个 clone 里解析不成一棵树：${String(e.message).slice(0, 200)}`);
  }
}

/**
 * 把 SOURCES 那几份源提到 `<tmp>/<tree>/templates/nextjs/scripts/…`，返回 `sheet-recipes.js` 的绝对路径。
 * 🔴 先写进 `.tmp.<pid>` 再 rename：被打断的那次留下的半个目录，跟提完的目录长得一模一样，
 *    而下一次会直接拿它当缓存用。
 * 🔴 缓存命中的判据是 **SOURCES 里每一份都在**，不是「sheet-recipes.js 在就算提好了」。
 *    目录名只带树的 sha，而目录**内容**还取决于 SOURCES 这张清单 —— 于是往清单里加一份源
 *    不会让任何已经存在的缓存目录失效。#1016 r4 实测：同一棵树在改清单**之前**被提过一次，
 *    改完之后那 80 份表全部报 `Cannot find module '../theme-presets.js'`，清单加了等于没加。
 * 🔴 #1095 —— **那个 symlink 通不通也算进「提好了」**。以前 `complete()` 只看源在不在，而失败那一次
 *    留下的目录里源是齐的（symlink 指向不存在的目录也创建得成功，是个断链），于是下一次调用直接跳过
 *    整个准备段、继续用那条断链，**改对了也还是红**。判据用 `fs.existsSync`（它跟着 symlink 走），
 *    所以断链和目录被删掉两种情况都会重新提一次。
 */
function exportSources(tree) {
  const dir = path.join(os.tmpdir(), `theme-sheet-fresh-${tree}`);
  const complete = () => SOURCES.every((rel) => fs.existsSync(path.join(dir, rel)))
    && fs.existsSync(path.join(dir, 'templates', 'nextjs', 'node_modules', 'postcss'));
  if (!complete()) {
    // 🔴 先把 node_modules 找到再动手提源：找不到是 die(2)，而那时若已经建了 stage 目录就会留一份垃圾在
    //    /tmp 里（而且它源是齐的，正好是上面那条 #1095 注释说的那种会被误当缓存的形状）。
    const nodeModules = resolveNodeModules();
    const stage = `${dir}.tmp.${process.pid}`;
    fs.rmSync(stage, { recursive: true, force: true });
    for (const rel of SOURCES) {
      let blob;
      try {
        blob = execFileSync('git', ['cat-file', '-p', `${tree}:${rel}`], { cwd: REPO, maxBuffer: 1 << 28 });
      } catch (e) {
        fs.rmSync(stage, { recursive: true, force: true });
        return die(`树 ${tree} 里没有 ${rel} —— 这棵树读不出一份表的源，什么都没验成`);
      }
      fs.mkdirSync(path.join(stage, path.dirname(rel)), { recursive: true });
      fs.writeFileSync(path.join(stage, rel), blob);
    }
    // `theme-css-lint.js` 顶上 require('postcss')。node_modules 不在任何一棵树里（.gitignore），
    // 所以它只能从别处借 —— 借的是解释器的依赖，不是被判对象的源。从哪儿借、以及找不到时怎么办，
    // 整段写在上面的 resolveNodeModules()（#1095）。
    fs.symlinkSync(nodeModules, path.join(stage, 'templates', 'nextjs', 'node_modules'));
    // 提齐了才去动那个不完整的旧目录 —— 删和 rename 挨着做，窗口尽量小。
    fs.rmSync(dir, { recursive: true, force: true });
    try {
      fs.renameSync(stage, dir);
    } catch (e) {
      // 另一次调用抢先提完了（守卫逐个文件叫，80 次是串行的，但别把这当保证）。
      fs.rmSync(stage, { recursive: true, force: true });
      if (!complete()) throw e;
    }
  }
  return path.join(dir, RECIPES);
}

/** 一份表的全部内容 = 横幅 + `sheetFor(i, seed)`。横幅的格式跟 generate.js:86 逐字一致。 */
function render(sheetFor, id, seed, i) {
  return `/* theme-css-contract: v1\n   ${id} — generated by scripts/theme-pipeline/generate.js`
    + ` (#1004; all 34 blocks since #1051). */\n\n${sheetFor(i, seed)}`;
}

function main() {
  const argv = process.argv.slice(2);
  const arg = (name) => {
    const i = argv.indexOf(name);
    return i >= 0 ? argv[i + 1] : undefined;
  };
  const ref = arg('--tree');
  const file = arg('--file');
  const check = argv.includes('--check');
  if (!ref || !file) die('用法：--tree <tree-ish|index> --file <仓库根起算的路径> [--check]');

  const tree = resolveTree(ref);
  let disk;
  try {
    disk = git(['cat-file', '-p', `${tree}:${file}`]);
  } catch (e) {
    return die(`树 ${tree} 里没有 ${file}`);
  }

  // 🔴 候选号是这份表**自己**带的，不是从文件名推的：文件名在 promote 那一步被改成了池 id
  //    （`gen-07-1` → `magenta-01`），而生成器的输入是候选号里那两个数。
  const m = /^\/\* theme-css-contract: v1\n {3}gen-(\d+)-(\d+) — generated by/.exec(disk);
  if (!m) {
    return die(`${file} 的横幅里没有 \`gen-<seed>-<n>\` 这个候选号 —— 复算不出它该长什么样`);
  }
  const seed = Number(m[1]);
  const i = Number(m[2]) - 1;

  const { sheetFor } = require(exportSources(tree));
  const want = render(sheetFor, `gen-${m[1]}-${m[2]}`, seed, i);

  if (check) {
    if (want === disk) {
      process.stdout.write(`✅ ${file} 跟树 ${tree} 里的配方对得上\n`);
      return 0;
    }
    process.stderr.write(`🔴 ${file} 跟树 ${tree} 里的配方对不上（候选 gen-${m[1]}-${m[2]}）\n`);
    return 1;
  }

  const abs = path.join(REPO, file);
  fs.writeFileSync(abs, want);
  process.stdout.write(`重新生成了 ${file}（候选 gen-${m[1]}-${m[2]}，源取自树 ${tree}）\n`);
  return 0;
}

// 🔴 崩溃要退 **2**，不是 node 默认的 1（#1016 r4）。这个文件头上写的约定是「0 对得上 · 1 过期了 ·
//    2 什么都没验成」，而未捕获异常在 node 里退 1 ⟹ 落进「过期了」那一桶。叫它的那家守卫
//    （`ai-team/dispatcher/ship-check-testmap-fresh.sh:286-289`）据这个数分桶，1 那一桶会打出
//    「重新生成再 re-stage」—— 而它自己专门把「没验成」单独分了一桶、还注掉了这条建议，逐字写着
//    regenerating is exactly the wrong thing。少一个 module、读不到那棵树，重新生成一次都救不了。
//    被委托的脚本不守约定，等于把调用方那份用心作废。（`die()` 早就退 2；缺的是这一层。）
try {
  process.exit(main());
} catch (e) {
  process.stderr.write(`🔴 ${e && e.stack ? e.stack : String(e)}\n`);
  process.stderr.write('🔴 这一格什么都没验成（不是「过期了」）—— 别重新生成，先读上面那条报错。\n');
  process.exit(2);
}
