#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const siteDir = path.join(rootDir, 'site');

if (!fs.existsSync(siteDir) || !fs.existsSync(path.join(siteDir, 'brand.json'))) {
  console.error(`Site config not found: ${siteDir}/brand.json`);
  process.exit(1);
}

console.log('Syncing site config...');

// ── Aggregate blog posts ──────────────────────────────────────────────────────

const blogDir = path.join(siteDir, 'blog');
let blogPosts = [];

if (fs.existsSync(blogDir)) {
  const blogFiles = fs.readdirSync(blogDir).filter(f => f.endsWith('.json'));
  for (const file of blogFiles) {
    const content = JSON.parse(fs.readFileSync(path.join(blogDir, file), 'utf-8'));
    blogPosts.push(content);
  }
  blogPosts.sort((a, b) => new Date(b.publishedAt).getTime() - new Date(a.publishedAt).getTime());
  console.log(`  Found ${blogPosts.length} blog post(s)`);
}

// ── Aggregate pages (recursive — supports subdirectories) ─────────────────────

const pagesDir = path.join(siteDir, 'pages');
let allPages = [];

function readPagesRecursive(dir, prefix) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      readPagesRecursive(path.join(dir, entry.name), prefix ? `${prefix}/${entry.name}` : entry.name);
    } else if (entry.name.endsWith('.json')) {
      const content = JSON.parse(fs.readFileSync(path.join(dir, entry.name), 'utf-8'));
      if (prefix) {
        const baseName = entry.name.replace(/\.json$/, '');
        content.slug = `${prefix}/${baseName}`;
      }
      allPages.push(content);
    }
  }
}

if (fs.existsSync(pagesDir)) {
  readPagesRecursive(pagesDir, '');
  allPages.sort((a, b) => (a.navOrder ?? 99) - (b.navOrder ?? 99));
  console.log(`  Found ${allPages.length} page(s)`);
}

// ── Auto-generate navigation.json ─────────────────────────────────────────────

const navPath = path.join(siteDir, 'navigation.json');
const existingNav = JSON.parse(fs.readFileSync(navPath, 'utf-8'));

const nonHomePages = allPages.filter(p => p.slug !== 'home');
const isServiceDetailPage = p => p.serviceDetailPage === true || (p.slug.startsWith('services/') && p.slug !== 'services');
const isKeywordPage = p => (p.keywordPage === true || p.slug.includes('/')) && !isServiceDetailPage(p);
const regularPages = nonHomePages.filter(p => !isKeywordPage(p) && !isServiceDetailPage(p));
const keywordPages = nonHomePages.filter(p => isKeywordPage(p));

// Header links: regular pages only (keyword pages excluded — too many for header)
const ctaSlug = existingNav.header.cta.href.replace(/^\//, '');
const headerLinks = [
  { label: 'Home', href: '/' },
  ...regularPages
    .filter(p => p.navLabel && p.slug !== ctaSlug)
    .map(p => ({ label: p.navLabel, href: `/${p.slug}` }))
];

// Footer: Quick Links (regular pages) + keyword pages in existing extra columns
const footerLinks = [
  { label: 'Home', href: '/' },
  ...regularPages
    .filter(p => p.navLabel)
    .map(p => ({ label: p.navLabel, href: `/${p.slug}` }))
];

existingNav.header.links = headerLinks;
if (existingNav.footer.columns.length > 0) {
  existingNav.footer.columns[0].links = footerLinks;
}

// Group keyword pages by service — one footer column per service
const hasKeywordColumns = existingNav.footer.columns.some(c => c.title !== 'Quick Links');
if (keywordPages.length > 0 && !hasKeywordColumns) {
  const groups = {};
  for (const p of keywordPages) {
    const serviceSlug = p.slug.split('/')[0];
    if (!groups[serviceSlug]) groups[serviceSlug] = [];
    groups[serviceSlug].push(p);
  }
  for (const [serviceSlug, pages] of Object.entries(groups)) {
    existingNav.footer.columns.push({
      title: serviceSlug.replace(/-/g, ' ').replace(/\b\w/g, c => c.toUpperCase()),
      links: pages.slice(0, 6).map(p => ({ label: p.title, href: `/${p.slug}` })),
    });
  }
}

// Write updated navigation back to site/ (in-place)
fs.writeFileSync(navPath, JSON.stringify(existingNav, null, 2));
console.log('  Regenerated navigation.json');

// ── Generate src/lib/config-data.ts ───────────────────────────────────────────

const brand = JSON.parse(fs.readFileSync(path.join(siteDir, 'brand.json'), 'utf-8'));
const navigation = existingNav; // already in memory
const seo = JSON.parse(fs.readFileSync(path.join(siteDir, 'seo.json'), 'utf-8'));
const services = JSON.parse(fs.readFileSync(path.join(siteDir, 'services.json'), 'utf-8'));

const configDataPath = path.join(rootDir, 'src', 'lib', 'config-data.ts');
const tsContent = `// Auto-generated by sync-config.js — do not edit manually
export const brand = ${JSON.stringify(brand)};
export const navigation = ${JSON.stringify(navigation)};
export const seo = ${JSON.stringify(seo)};
export const services = ${JSON.stringify(services)};
export const blogPosts = ${JSON.stringify(blogPosts)};
export const allPages = ${JSON.stringify(allPages)};
`;
fs.writeFileSync(configDataPath, tsContent);
console.log('  Generated src/lib/config-data.ts');
