#!/usr/bin/env node

// sync-config.js —— 发布模式的构建前那一步（#1666 起只剩这一段；派生和校验在 `derive-site.js`）。
//
//   1. 跑 `derive-site.js`：菜单、css、校验，全套（这份文件原来的全部正文，`git log --follow scripts/derive-site.js`）。
//      不给 `AI1ST_RENDER` = publish ⟹ site.css 照旧剪、<lastmod> 照旧取 git 提交时间。
//   2. 这次构建发布到哪个地址、收不收录（SITE_URL / SITE_INDEXABLE，#1547）—— 只有发布用得上。
//   3. 拼 `src/lib/config-data.ts`。#1665 起页面每次从 site/ 读（`src/lib/site-data.server.ts`），`src/` 里已经没人
//      import 它；留着是为了 `lib/site-data.test.js` 那条「请求时拼的跟构建时拼的逐字段相同」的对照，以及还在
//      读它的工具（theme-gallery）。预览那条路（worker / entrypoint / 建站各阶段）只跑 derive-site.js，不碰这份文件 ——
//      所以「保存一笔，config-data.ts 改动时间不变」。
//
// 调用方：`npm run dev` / `npm run build`（predev / prebuild）· worker §deployWorktreeScript（发布那次构建）·
//   老路（#1665 之前的模板）的那几处 —— 它们站仓里没有 derive-site.js，跑的是自己那份老 sync-config.js。

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

require('./derive-site.js').ready.then((d) => {
  // #1547 — 这次构建发布到哪个地址、收不收录，由 manager 经 env 给（SITE_URL / SITE_INDEXABLE）；
  // 覆盖每个语言的 seo.domain / seo.indexable。规则与「两个都缺 = 原样」的理由在 lib/build-target.js。
  {
    const { readBuildTarget, applyBuildTarget } = require('./lib/build-target.js');
    let target;
    try {
      target = readBuildTarget(process.env);
    } catch (e) {
      console.error(`🔴 ${e.message}`);
      process.exit(1);
    }
    applyBuildTarget(d.seoByLocale, target);
    console.log(`  Build target: ${target.siteUrl ?? '(SITE_URL 未给，用 seo.json 原值)'}`
      + ` · indexable=${target.indexable ?? '(未给)'}`);
  }

  // TICKET-268b: build-time env overrides site_meta (lets the deploy pick the env's manager URL).
  const resolvedLeadApi = process.env.NEXT_PUBLIC_LEAD_API || d.leadApi || '';
  const tsContent = `// Auto-generated by sync-config.js — do not edit manually
export const siteId = ${JSON.stringify(d.siteId)};
export const leadApi = ${JSON.stringify(resolvedLeadApi)};
export const colorScheme = ${JSON.stringify(d.colorScheme)};
export const dir = ${JSON.stringify(d.dir)};
export const defaultLocale = ${JSON.stringify(d.defaultLocale)};
export const locales = ${JSON.stringify(d.locales)};
export const brand = ${JSON.stringify(d.brand)};
export const seoByLocale = ${JSON.stringify(d.seoByLocale)};
export const servicesByLocale = ${JSON.stringify(d.servicesByLocale)};
export const formsByLocale = ${JSON.stringify(d.formsByLocale)};
export const navigationByLocale = ${JSON.stringify(d.navigationByLocale)};
export const pagesByLocale = ${JSON.stringify(d.pagesByLocale)};
export const blogPostsByLocale = ${JSON.stringify(d.blogPostsByLocale)};
export const regions = ${JSON.stringify(d.regions)};
export const pageLayout = ${JSON.stringify(d.pageLayout)};
`;
  fs.writeFileSync(path.join(rootDir, 'src', 'lib', 'config-data.ts'), tsContent);
  console.log('  Generated src/lib/config-data.ts');
});
